use_frameworks!

platform :ios, '8.0'

target 'CDPickerOperation_Example' do
  pod 'CDPickerOperation', :path => '../'

  target 'CDPickerOperation_Tests' do
    inherit! :search_paths

    
  end
end
